sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "EGR72biPK6ob/UR4ATPNvDLGz69SPPRawj6WpTZs0g2dDchzVwvS/ilm7kJe/RYGDL3WDyH86LO875tdLDnRcl33ztCUdZ60bwpPKvFjtH3MvuzstuQqU/22mWU+Be7dPIOCpBMIisP3lLwSIPDqVGZfB0VxrxBFtOacQ9BFe02xEEIQGAWpqlOwkjeeFH0/JidCRjUjN3Ud3D2Vv8fWU5kSFz9fPciFwXkH/lsgXpn5mANn+QtqDIcKxPlEhi2gwDKYZVTckSKOVDGhEripVuPYnq4WbiVuiazjJkzWuMMTMariu/Su6tjBKXv+fX/F6AD4gebNnnH+SbEM/dKAjPB+szgpagzJMmZAK9jtMHx/+31tqQ1g/dUAI6b3yzFp2r7C3zcuNatIev3yUWGoXAYQnmIdWmZeLTIioWn7hsQ6SaAKg62ywBFNzjEHVItNfcMUoNLlJ9qiZnAfD3ufhfqXjM46beAI+xhKU2sm1tATtSbqHreC2AyCmRCNACuvlLlFT8JxOm04LKwBjGQ3EbCCCn2c2+0i5ddUt+LXCm2GK4Ho8hy01l9PSv1A9dqamlPiTq6sJxJPm+1M2TLuccE/TIxTktm64DFGDcDSI0KwDa5kwSYAOzUWtgupvK1Ntg0RQp3uiyfVo8ExWjGOLXbpyCgnZt+/hp9m+yeakCk="
  - secure: "SBEMBDtI2h8X1Rd1bB6g+jNkYtheXYEjPEjQ5qwDydHEITYYB9KMiSBK9swHXDvU2XH8hgDAj5PhyvCAUnK2v8wiCEZuaFGMeP2+33Prbn7cqTAdW1VlKPmoQOpa117+jFanIb+3ltehI60PrX7cy+z03i7exqKiIeDUzA6d5KhgFF8kzABPGbfmE8jZLtogmstNRxzkMoFRKq8nd/DfGDMmeOnH508EOS+OOo0fD/8UjSdeXg6nbR8IxsXQr4CImcVk3H01i3qoaCv6zUZ2mA83nHsNaHIw/epbm61GOEJ6u9/h1tvN5XYHiZOqKWd8NqT11jvV/luMlJaZT3Fr7x4LT3cmAyJ0bi0hiuTHtJHPBgN9VLUnP9D/ccZ/MErL7zvASekrR6UaDC88roha4UGKfGnIKD9tsy4mRXFnpYHvIYrjg0+KmZZMvpBfTm6Z3Yepq2t7g5v3Y8PL4JNqDMFNG3cztfNraK5GCYMA5sp1cligbX9Ek7/H8S9Loo9CtiQcysHZsmHwiOKOxWxGCFsOUCNcgOMU3FJ2AoiqkXDyniLfQXHJ5Pd0tCYqISam9mqynusJT5bVzqrehFt+40kqtjY0hQSrDJQSEh8Zd+NHxHk5vwsEfVawsENeTA+bZrWBbbug1fRPQyF1NqZds4cigdot8qe4wEQmqblfveU="
  - secure: "qaOAjLuG+JyyamtKn3f5M+/3SqBTgFxofewwJHQmuHCzwOTcuP0kRtdGv3fiWh+Fq6Fr5w3FODB2aWk7TMcO/iFSqfu0E4FaOgSuXkcmjWBC/XfyJ9cs7jdtVm5NDh83eUx1xn4QeCLpyO503lVw9N1z5omZxhv7jQbEakhlCOyho0kIv2mgTcdeXMxItXIroQ7UPTghPgsjS7reVZLCDPm+2pY68vkl35dLOD+r8xKgSimCaP4YSAWi3nR2lPAd3eNs1sEw+WGRUQS2euNFEOHTL/gF6CO0b+lUN7TQCwyL2CAFJWQEbdmUJYkyfQ9PlKUfu2twaZbKE46GciPFNH75zjzq3Zjmv8lSb2DmVekr0qmeCPAUjUcuz1CVc4KLsBdrq1p2FuzfNutiIsVSIIuyhk6z5CjZxWnPDuc2TZF7rpd5m18TjWTky/qVZplWJwpL7G6o0/lyiS6Q1/m0mZtnnTxAHnF+N9wMwiQ9JcGoG9GuOkg+MxmbFwcQXJQxCeE5x+9PvB/PkTUuM1FDqc/GMS+astlx3Y8YA40rQOkKowuosmgaXs+AwoLbDVI+x4isNYwwq/XAPOt/khuaiGobc9RP4XH1BZhKmQqYyNsvzftZXkbrI2QwPgblCEVTcgEslMRZq8flWF9mmUFvoLzQzohkC6nnGSUWEHOcztA="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
